package Vista.GUI;

import civitas.Casilla;
import civitas.Tablero;

/**
 *
 * @author manuel
 */
public class CasillaPanel extends javax.swing.JPanel {

    Casilla casilla;
    
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }
    
    public void setCasilla(Casilla c){
        this.casilla = c;
        this.numeroCasilla.setText(Integer.toString(this.casilla.getNumero()));
        this.nombreCasilla.setText(this.casilla.getNombre());
        this.repaint();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casilla = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        numeroCasilla = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        nombreCasilla = new javax.swing.JLabel();

        Casilla.setText("CASILLA");
        Casilla.setEnabled(false);

        Nombre.setText("NOMBRE");
        Nombre.setEnabled(false);

        numeroCasilla.setText("0");

        Nombre1.setText("NUMERO");
        Nombre1.setEnabled(false);

        nombreCasilla.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(nombreCasilla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroCasilla)))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(Casilla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Casilla)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1)
                    .addComponent(numeroCasilla))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(nombreCasilla))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casilla;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel nombreCasilla;
    private javax.swing.JLabel numeroCasilla;
    // End of variables declaration//GEN-END:variables
}
