package Vista.GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author manuel
 */
public class PropiedadPanel extends javax.swing.JPanel {

    TituloPropiedad titulo;
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    public void setPropiedad(TituloPropiedad t){
        this.titulo = t;
        this.nombreTitulo.setText(titulo.getNombre());
        this.hipotecadaTitulo.setText(Boolean.toString(titulo.getHipotecado()));
        this.casasTitulo.setText(Integer.toString(titulo.getNumCasas()));
        this.hotelesTitulo.setText(Integer.toString(titulo.getNumHoteles()));
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        nombreTitulo = new javax.swing.JLabel();
        Hipotecada = new javax.swing.JLabel();
        hipotecadaTitulo = new javax.swing.JLabel();
        Casas = new javax.swing.JLabel();
        Hoteles = new javax.swing.JLabel();
        casasTitulo = new javax.swing.JLabel();
        hotelesTitulo = new javax.swing.JLabel();

        Titulo.setText("TITULO");
        Titulo.setEnabled(false);

        nombreTitulo.setText("NombreTitulo");

        Hipotecada.setText("HIPOTECADA");
        Hipotecada.setEnabled(false);

        hipotecadaTitulo.setText("true");

        Casas.setText("CASAS");
        Casas.setEnabled(false);

        Hoteles.setText("HOTELES");
        Hoteles.setEnabled(false);

        casasTitulo.setText("0");

        hotelesTitulo.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hipotecada))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreTitulo)
                        .addGap(44, 44, 44)
                        .addComponent(hipotecadaTitulo)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(Casas)
                        .addGap(31, 31, 31)
                        .addComponent(Hoteles)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(casasTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hotelesTitulo)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(Hipotecada)
                    .addComponent(Casas)
                    .addComponent(Hoteles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTitulo)
                    .addComponent(hipotecadaTitulo)
                    .addComponent(casasTitulo)
                    .addComponent(hotelesTitulo))
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casas;
    private javax.swing.JLabel Hipotecada;
    private javax.swing.JLabel Hoteles;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel casasTitulo;
    private javax.swing.JLabel hipotecadaTitulo;
    private javax.swing.JLabel hotelesTitulo;
    private javax.swing.JLabel nombreTitulo;
    // End of variables declaration//GEN-END:variables
}
